name: uber_rider_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  firebase_database: ^10.4.5
  fluttertoast: ^8.2.4
  google_maps_flutter: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/car_android.png
    - assets/images/car_ios.png
    - assets/images/desticon.png
    - assets/images/desticon1.png
    - assets/images/logo.png
    - assets/images/logo1.png
    - assets/images/pickicon.png
    - assets/images/posimarker.png
    - assets/images/redmarker.png
    - assets/images/taxi.png
    - assets/images/user_icon.png

  fonts:
    - family: Signatra
      fonts:
        - asset: assets/fonts/Signatra.ttf
    - family: Brand-Regular
      fonts:
        - asset: assets/fonts/bolt-regular.ttf
    - family: Brand Bold
      fonts:
        - asset: assets/fonts/bolt-semibold.ttf



  