// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBleXjzHukDCpS_-EjENqi65AG8Y0_xWRg',
    appId: '1:802605304600:web:2b1ce3aa12ea6b949c2c6d',
    messagingSenderId: '802605304600',
    projectId: 'uber-app-d4bbe',
    authDomain: 'uber-app-d4bbe.firebaseapp.com',
    databaseURL: 'https://uber-app-d4bbe-default-rtdb.firebaseio.com',
    storageBucket: 'uber-app-d4bbe.appspot.com',
    measurementId: 'G-BMGTE96CM5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCElvY8cZoUP76dPM-nN64bdYf8QYUhyLw',
    appId: '1:802605304600:android:d29923988933b2d99c2c6d',
    messagingSenderId: '802605304600',
    projectId: 'uber-app-d4bbe',
    databaseURL: 'https://uber-app-d4bbe-default-rtdb.firebaseio.com',
    storageBucket: 'uber-app-d4bbe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCS4Q6jbS5B3PhGcr_rMJvTT0ThjoMO9f0',
    appId: '1:802605304600:ios:21859df5fa603ca49c2c6d',
    messagingSenderId: '802605304600',
    projectId: 'uber-app-d4bbe',
    databaseURL: 'https://uber-app-d4bbe-default-rtdb.firebaseio.com',
    storageBucket: 'uber-app-d4bbe.appspot.com',
    iosBundleId: 'com.example.uberRiderApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCS4Q6jbS5B3PhGcr_rMJvTT0ThjoMO9f0',
    appId: '1:802605304600:ios:02ec58e53375506b9c2c6d',
    messagingSenderId: '802605304600',
    projectId: 'uber-app-d4bbe',
    databaseURL: 'https://uber-app-d4bbe-default-rtdb.firebaseio.com',
    storageBucket: 'uber-app-d4bbe.appspot.com',
    iosBundleId: 'com.example.uberRiderApp.RunnerTests',
  );
}
